stages:
  - build
  - release

build:
  stage: build
  only:
    - tags
  except:
    - commissioning
  cache:
    paths:
      - node_modules/
  script:
    - export PATH=/home/here/user/bin/:$PATH
    - export npm_config_cache=$(mktemp -d) 
    - npm install
    - npx ng build --prod
  tags:
    - node
  artifacts:
    paths:
      - dist/

release:
  stage: release
  only:
    - tags
  except:
    - commissioning
  variables:
    APP_DIR: /ride/release/python/webapps/startup/frontend
  script:
    - mkdir -p $APP_DIR
    - rm -rf $APP_DIR/*
    - cp -r dist/* $APP_DIR/